{ lib, stdenv }:

{ p4Source, ... } @ args:


with builtins;
with lib;

let

  # This is the set representing the possible targets (eg top-level packages)
  # that can be automatically deployed using nix. This is a purely nix->P4
  # syntax mapper.
  targets_mapping = { v1switch="V1Switch"; };

  p4_attr = (lib.evalModules {
    modules = [ 
      ./transpiler-module.nix 
      { config = p4Source; }
    ];
  }).config;

  # include = list of includes
  mkInclude = include: concatStringsSep "\n" (map (x: "#include <" + x + ">") include);

  # define = list of attr of name and value
  mkDefine = define:  concatStringsSep "\n"  (imap1 (i: v: "#define "
  + v.name + " " + v.value) define);

  # headers.typedef = attrset of type and name
  mkTypedef = typedef: concatStringsSep "\n"  (mapAttrsToList (name: value:
  "typedef " + value + " " + name + ";") typedef);

  # headers.const = attrset of type, name and value
  mkConst = const: concatStringsSep "\n"  (mapAttrsToList (name: value: "const "
  + value.type + " " + name + " = " + value.value + ";") const);

  # headers.struct = attrset of name and content
  mkHeader = header: (mapAttrsToList (name: value: "struct " + name + " {\n " +
  (concatStringsSep "\n" (flatten (imap 1 (_: v: (mapAttrsToList (name: value: 
  "    " + value + " " + name + ";\n") v)) value.content))) + "}\n" ) header );

  # headers.header = attrset of name and content
  # same as struct but limited to bitfield and int  
  mkHeader = header: (mapAttrsToList (name: value: (if (value.union) then
  "header_union " else "header ") + name + " {\n " + (concatStringsSep "\n"
  (flatten (imap 1 (_: v: (mapAttrsToList (name: value: "    " + value + " " +
  name + ";\n") v)) value.content))) + "}\n" ) header );

  # headers.enum = attrset of name and content
  mkEnum = enum: concatStringsSep "\n"  (mapAttrsToList (name: value: "enum " +
  name + " { " + (concatStringsSep ", " value) + " }") enum)

  # headers.error = list of possible errors
  mkError = error: "error { " + (concatStringsSep ", " error) + " };";



  # TODO: check for attrset sanity
  mkHeaders = include: headers: ''
    /* This file has been auto-generated by Nix, do not edit it manually! */
    ${mkInclude include} 

    ${mkConst headers.const}

    ${mkTypedef headers.typedef}

    ${mkHeader headers.header}

    
    ${mkStruct headers.struct}

    ${mkEnum headers.enum}

    ${mkError headers.error}

    ${headers.additional_headers}
    '';

  # TODO: add v1switch and other targets there!
  #mkTarget =  then

  # TODO: port to logic. namespace
  #mkCallStack = call_stack: removeSuffix ",\n" (concatStringsSep "(),\n" call_stack);

  # XXX: I am assuming that if you want to setup a target you want it to be the
  # main logic, does this assumption always holds true?
  mkTarget = p4Source: targets_mapping.${p4Source.target} + "(\n" + (mkCallStack
  p4Source.call_stack) + "\n) main;";

  mkSource = mkHeaders p4_attr.include p4_attr.headers;
in
  # something like this
  #includes = headers.include ++ optionals (target.name == "v1switch") [ "v1model.p4" ];
  #p4_attr
  mkSource
