{ lib, stdenv }:

{ p4Source, ... }@args:

with builtins;
with lib;

let

  # This is the set representing the possible targets (eg top-level packages)
  # that can be automatically deployed using nix. This is a purely nix->P4
  # syntax mapper.
  targets_mapping = { v1switch = "V1Switch";
                      ebpf = "ebpfFilter";
                      psa = "PSA_Switch";
                    };

  #TODO: add additional fields and checks here, eg include for v1switch target!

  # This ensures the argument given as p4Source is correctly-typed and add defaults
  # to the attrset given as need be so the function below can work with correct
  # assumptions.
  p4_attr = (lib.evalModules {
    modules = [ ./transpiler-module.nix { config = p4Source; } ];
  }).config;

  # All of the functions below are mostly fancy wrappers for adding
  # constants or set types that cannot be changed and are usually in global
  # scope.

  # include = list of includes
  mkInclude = include:
    concatStringsSep "\n" (map (x: "#include <" + x + ">") include);

  # define = list of attr of name and value
  mkDefine = define:
    concatStringsSep "\n"
    (mapAttrsToList (name: value: "#define " + name + " " + value) define);

  # headers.typedef = attrset of type and name
  mkTypedef = typedef:
    concatStringsSep "\n"
      (mapAttrsToList (name: value: "typedef " + value + " " + name + ";")
        typedef);

  # headers.const = attrset of type, name and value
  mkConst = const:
    concatStringsSep "\n" (mapAttrsToList (name: value:
      "const " + value.type + " " + name + " = " + value.value + ";") const);

  # headers.struct = attrset of name and content
  mkStruct = header:
    concatStringsSep "\n\n" (mapAttrsToList (name: value:
      "struct " + name + " {\n " + (concatStringsSep "\n" (flatten (imap1 (_: v:
        (mapAttrsToList (name: value: "    " + value + " " + name + ";") v)
       ) value.content))) + "\n}" ) header);

  # headers.header = attrset of name and content
  # same as struct but limited to bitfield and int  
  mkHeader = header:
    concatStringsSep "\n\n" (mapAttrsToList (name: value:
      (if (value.union) then "header_union " else "header ") 
        + name + " {\n " + 
        (concatStringsSep "\n" (flatten (imap1 (_: v:
          (mapAttrsToList (name: value: "    " + value + " " + name + ";") v)
        ) value.content))) + "\n}" ) header);

  # headers.enum = attrset of name and content
  mkEnum = enum:
    concatStringsSep "\n" (mapAttrsToList (name: value:
      "enum " + name + " { " + (concatStringsSep ", " value) + " }") enum);

  # headers.error = list of possible errors
  mkError = error:
    if (error != [ ]) then
      "error { " + (concatStringsSep ", " error) + " };"
    else
      "";

  # TODO: maybe we should allow the user to control the scope depth of the
  # define...?
  mkHeaders = include: define: headers: ''
    /* This file has been auto-generated by Nix, do not edit it manually! */
    ${mkInclude include} 

    ${mkDefine define} 

    ${mkConst headers.const}

    ${mkTypedef headers.typedef}

    ${mkHeader headers.header}

    ${mkStruct headers.struct}

    ${mkEnum headers.enum}

    ${mkError headers.error}

    ${headers.additional_headers}
  '';

  # logic: list of attrset of name and value. See transpiler-module for the
  # reasoning behind the format of this and other parts of the transpiler.
  mkLogic = logic:
    concatStringsSep "\n\n"
    (imap1 (_: v: (concatStringsSep "" (mapAttrsToList (name: value: (if value
    == null then "" else value)) v)))
      logic);

  # Creates the global main scope of the P4 program with the logic defined.
  mkTarget = target: logic:
    if (target != "null") then
      targets_mapping.${target} + ''
        (
      '' + mkCallStack logic + ''

        ) main;''
    else "";

  # Concatenates the logic functions into a single sequential block.
  mkCallStack = logic:
    concatStringsSep "," (imap1 (_: v: (concatStringsSep "" (mapAttrsToList (name: value: name + (if
    value == null then "" else "()")) v)))
      logic);

  mkTargetSub = sub: 
    concatStringsSep "\n" (mapAttrsToList (name: value: name + "(" + (mkCallStack value.content) + ")
    " + value.name + ";" ) sub);

  mkSub = sub:
    concatStringsSep "\n\n" (mapAttrsToList (name: value: (
    concatStringsSep "\n\n"
    (imap1 (_: v: (concatStringsSep "" (mapAttrsToList (name: value: value) v)))
    value.content)))
      sub);

  # Final assembly of the source file needed to, eg, create a derivation.
  mkSource = ''
    ${mkHeaders p4_attr.include p4_attr.define p4_attr.headers}

    ${mkLogic p4_attr.logic.main}

    ${mkSub p4_attr.logic.sub}

    ${mkTargetSub p4_attr.logic.sub}

    ${mkTarget p4_attr.target p4_attr.logic.main}
  '';
in 
  mkSource
